# Generated by Django 5.2 on 2025-04-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(max_length=3)),
                ('boleto', models.IntegerField(max_length=9)),
                ('internacao', models.DateTimeField(auto_now_add=True)),
                ('alta', models.DateTimeField(auto_now_add=True)),
                ('sala', models.CharField(choices=[('EM', 'EMERGENCIA'), ('CM', 'CLINICA MÉDICA'), ('CC', 'CENTRO CIRÚRGICO')], max_length=2)),
                ('procedimento', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
