# Generated by Django 5.2 on 2025-04-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_painel_hegv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leito',
            name='boleto',
        ),
        migrations.AddField(
            model_name='leito',
            name='boletim',
            field=models.IntegerField(max_length=9, null=True),
        ),
    ]
