# Generated by Django 5.2 on 2025-04-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_painel_hegv', '0002_remove_leito_boleto_leito_boletim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leito',
            name='alta',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='leito',
            name='internacao',
            field=models.DateTimeField(null=True),
        ),
    ]
