# Generated by Django 5.2 on 2025-04-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_painel_hegv', '0003_alter_leito_alta_alter_leito_internacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='leito',
            name='paciente',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
