# Generated by Django 5.2 on 2025-04-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_painel_hegv', '0004_leito_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leito',
            name='sala',
            field=models.CharField(choices=[('AMA', 'SALA AMARELA'), ('CM', 'CLINICA MÉDICA'), ('CC', 'CENTRO CIRÚRGICO')], max_length=3),
        ),
    ]
