# Generated by Django 5.2.1 on 2025-05-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_painel_hegv', '0005_alter_leito_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leito',
            name='sala',
            field=models.CharField(choices=[('AMA', 'SALA AMARELA'), ('MIS', 'SALA VERDE MISTA'), ('CIR', 'CLINICA CIRÚRGICA')], max_length=3),
        ),
    ]
