# Generated by Django 5.2.1 on 2025-05-20 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_painel_hegv', '0006_alter_leito_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leito',
            name='boletim',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='leito',
            name='numero',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
