# Generated by Django 5.2.1 on 2025-05-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_painel_hegv', '0007_alter_leito_boletim_alter_leito_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaCirurgica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('vazia', 'Vazia'), ('cirurgia', 'Em Cirurgia'), ('higienizacao', 'Em Higienização')], default='vazia', max_length=15)),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
