# Generated by Django 5.2.1 on 2025-05-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_painel_hegv', '0008_salacirurgica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salacirurgica',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
