# Generated by Django 5.2 on 2025-05-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_painel_hegv', '0009_alter_salacirurgica_hora_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salacirurgica',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('cirurgia', 'Em Cirurgia'), ('higienizacao', 'Em Higienização')], default='vazia', max_length=15),
        ),
    ]
