# Generated by Django 5.2 on 2025-05-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_painel_hegv', '0010_alter_salacirurgica_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(choices=[('AMA', 'SALA AMARELA'), ('MIS', 'SALA VERDE MISTA'), ('CIR', 'CLINICA CIRÚRGICA')], max_length=3, unique=True)),
                ('horas_warning', models.IntegerField(default=24, help_text='Horas para passar de success para warning')),
                ('horas_danger', models.IntegerField(default=48, help_text='Horas para passar de warning para danger')),
            ],
        ),
    ]
